services:
  db-orders:
    image: mysql:8.0
    container_name: db-orders-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - orders-mysql-data:/var/lib/mysql
    networks:
      - orders-network

  api-orders:
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile
    container_name: api-orders-container
    restart: always
    ports:
      - "5002:8080"
      - "5003:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__OrderingConnectionString: "server=db-orders;port=3306;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD};"
    depends_on:
      - db-orders
    networks:
      - orders-network

volumes:
  orders-mysql-data:

networks:
  orders-network:
    external: false
